#!/usr/bin/env node
/**
 * Generates the environment variable table in docs/testing.md.
 *
 * Two of the four columns are facts only a person knows: what the material is, and where each
 * variable looks for it. The other two are not: which tests read a variable, and whether anything
 * still does. Those are read out of the test tree here, so the table cannot drift, and a variable that
 * no test uses any more cannot leave a table row behind. Run it with --check to fail instead of write,
 * which is what the test suite does.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const PAGE = join("docs", "testing.md");
const TESTS = "tests";
const BEGIN = "<!-- material-table:begin: generated by scripts/materials.mjs -->";
const END = "<!-- material-table:end -->";

/** What each variable is for, and where it looks. The tests decide the rest. */
const MATERIALS = [
  {
    variables: ["IMAGEFORGE_OTA_PACKAGE"],
    supplies: "a full OTA package (the one used here is a CPH2723 full OTA, 8.2 GB)",
    fallback: "those tests skip",
  },
  {
    variables: ["IMAGEFORGE_OTA_INIT_BOOT_SHA256"],
    supplies: "the digest the OTA's init_boot must have, an independent cross-check of the extraction",
    fallback: "the test skips",
  },
  {
    variables: [
      "IMAGEFORGE_ASTER_DUMP",
      "IMAGEFORGE_STOCK_IMAGE",
      "IMAGEFORGE_INIT_BOOT",
      "IMAGEFORGE_VENDOR_BOOT",
    ],
    supplies: "device dumps of the boot partitions",
    fallback: ".research/aster-validation/{boot,init_boot,vendor_boot}.img",
  },
  {
    variables: ["IMAGEFORGE_EROFS_DIGESTS", "IMAGEFORGE_PAYLOAD_DIGESTS", "IMAGEFORGE_EXT4_DIGESTS"],
    supplies:
      "sha256sum output captured on the device for files inside erofs and ext4 images, and for payload partitions",
    fallback:
      ".research/aster-validation/erofs-product-digests.txt, erofs-payload-digests.txt, ext4-vendor_dlkm-digests.txt",
  },
  {
    variables: ["IMAGEFORGE_BOOTANIMATION"],
    supplies: "a real vendor boot animation archive (the one used here came out of the OTA's my_product partition)",
    fallback: ".research/bootanimation/bootanimation.zip",
  },
  {
    variables: ["IMAGEFORGE_MTK_LOGO"],
    supplies: "a real MediaTek logo.img",
    fallback: ".research/mtk-logo/sample-logo.img",
  },
  {
    variables: ["IMAGEFORGE_LPMAKE"],
    supplies:
      "AOSP's lpmake, which the super image writer is compared against byte for byte (lpdump and lpunpack from the same package read its output back)",
    fallback: "/usr/bin/lpmake",
  },
  {
    variables: ["IMAGEFORGE_IMG2SIMG"],
    supplies: "AOSP's img2simg, which the sparse writer is compared against byte for byte",
    fallback: "/usr/bin/img2simg",
  },
  {
    variables: [
      "IMAGEFORGE_KERNELSU_MODULE",
      "IMAGEFORGE_KERNELSU_REFERENCE",
      "IMAGEFORGE_MAGISK_REFERENCE",
      "IMAGEFORGE_KPM_DIR",
      "IMAGEFORGE_TEST_KPM",
      "IMAGEFORGE_TEST_IMAGE",
    ],
    supplies: "the third party modules and stock images the patch providers are checked against",
    fallback: ".research/kpm, .research/images/...",
  },
];

function readTree(directory) {
  const files = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...readTree(path));
    else if (/\.tsx?$/.test(entry.name)) files.push(path);
  }
  return files;
}

/**
 * Which test files read each variable, as tests/unit/package rather than a path.
 *
 * Only an environment read counts. Matching the bare name would also catch an ordinary constant
 * that happens to start with IMAGEFORGE_, such as the identifier the wasm registry exports.
 */
function usage() {
  const used = new Map();
  for (const path of readTree(TESTS)) {
    const text = readFileSync(path, "utf8");
    const name = path.replace(/^tests\//, "").replace(/\.tsx?$/, "");
    const reads = [...text.matchAll(/process\.env(?:\.|\[\s*")(IMAGEFORGE_[A-Z0-9_]+)/g)].map(
      (match) => match[1],
    );
    for (const variable of new Set(reads)) {
      if (!used.has(variable)) used.set(variable, new Set());
      used.get(variable).add(name);
    }
  }
  return used;
}

function table() {
  const used = usage();
  const declared = new Set();
  const rows = [];
  for (const material of MATERIALS) {
    for (const variable of material.variables) declared.add(variable);
    const readers = new Set();
    for (const variable of material.variables) {
      for (const reader of used.get(variable) ?? []) readers.add(reader);
    }
    const names = material.variables.map((variable) => "`" + variable + "`").join(", ");
    const usedBy = [...readers].sort().map((reader) => "`" + reader + "`").join(", ") || "**nothing: stale row**";
    // a fallback is a path unless it is a sentence about skipping, and paths read better as code
    const fallback = /^(those|the test)/.test(material.fallback)
      ? material.fallback
      : "`" + material.fallback + "`";
    rows.push("| " + names + " | " + material.supplies + " | " + usedBy + " | " + fallback + " |");
  }

  const problems = [];
  for (const variable of used.keys()) {
    if (!declared.has(variable)) problems.push(variable + " is read by tests but not declared here");
  }
  for (const variable of declared) {
    if (!used.has(variable)) problems.push(variable + " is declared here but no test reads it");
  }
  if (problems.length > 0) {
    console.error(problems.join("\n"));
    process.exit(2);
  }

  return ["| Variable | Supplies | Used by | Default when unset |", "|---|---|---|---|", ...rows].join("\n");
}

function withGeneratedTable(page) {
  const begin = page.indexOf(BEGIN);
  const end = page.indexOf(END);
  if (begin < 0 || end < 0 || end < begin) {
    console.error("docs/testing.md has no material table markers");
    process.exit(2);
  }
  return page.slice(0, begin + BEGIN.length) + "\n\n" + table() + "\n\n" + page.slice(end);
}

const page = readFileSync(PAGE, "utf8");
const next = withGeneratedTable(page);
if (process.argv.includes("--check")) {
  if (next !== page) {
    console.error("docs/testing.md is out of date: run pnpm docs:materials");
    process.exit(1);
  }
  console.log("material table is up to date");
} else {
  writeFileSync(PAGE, next);
  console.log(next === page ? "material table unchanged" : "material table written");
}
